### ISSUE TITLE
promise.["catch"]  应该是 promise["catch"]  

### ISSUE THREAD

**Issue by ONEBOYS** [liubin/promises-book#18]
在2.5.1 http://liubin.github.io/promises-book/#_ie8

“而且很多压缩工具自带了将 promise.catch 转换为 promise.["catch"] 的功能”
promise.["catch"]  应该是 promise["catch"]  ，多了点号。

查看日文原文也有此笔误。

**Comment by liubin** [comment]
https://github.com/azu/promises-book/commit/2a958397dbdec49ddfbcc37f8778e9a9f7b0af49　
下次Releas修改

**Comment by liubin** [comment]
已fix，已发布1.4.1版本
