### ISSUE TITLE
"当然也有的Promise实现并没有内涵Promise"应该是“当然也有的Deferred实现并没有内涵Promise”

### ISSUE THREAD

**Issue by xuyang2** [liubin/promises-book#20]
在4.4.2 http://liubin.github.io/promises-book/#deferred-and-promise 中

“这是jQuery.Deferred结构的简化版。当然也有的Promise实现并没有内涵Promise。”
应该是 “当然也有的Deferred实现并没有内涵Promise。”

日文原文为
もちろんPromiseを持たないDeferredの実装もあります。

**Comment by liubin** [comment]
已fix，已发布1.4.1版本
