### ISSUE TITLE
中文版网页上的语言为 ja，应改为 zh-Hans，否则有些汉字很难看。

### ISSUE THREAD

**Issue by everbeen** [liubin/promises-book#21]
在此书[中文页面][book-zh]上，`<html>` 的 `lang` 属性值为 `ja`，浏览器会用日文字体进行渲染，导致有些日文中不存在的汉字不得不用中文字体进行渲染，就变得不整齐。

[book-zh]: http://liubin.github.io/promises-book/

应将上述属性改为:

```html
<html lang="zh-Hans">
```

**Comment by everbeen** [comment]
请看`迷你书`三个字。

![screen shot 2015-06-02 at 1 27 38 am](https://cloud.githubusercontent.com/assets/188089/7918815/b8c4d290-08c6-11e5-9a34-cae190e0a8aa.png)

**Comment by iplus26** [comment]
在作者更改前，可以通过浏览器设置 font-family: "Source Sans Pro" 来暂时解决这个问题

望及时修复。

**Comment by liubin** [comment]
了解，已经收到。

**Comment by liubin** [comment]
已经按 @everbeen 的方法修改。

同时感谢 @iplus26 。
